import nodemailer from 'nodemailer';

const API_BASE = `http://localhost:${process.env.PORT || 3200}/api/v1`;
const API_KEY = process.env.AGENT_API_KEY;

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT),
  secure: false, // STARTTLS
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

function formatDate(d = new Date()) {
  return d.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function buildHtml(digest) {
  const { date, overdueCount, tasksByPriority, agentActivity } = digest;

  const renderTasks = (tasks) =>
    tasks
      .map(
        (t) =>
          `<li><strong>${t.task}</strong> · ${t.domain || '—'} · ${t.agentId || 'unassigned'} · due ${t.dueDate || 'none'}</li>`
      )
      .join('\n');

  const agentRows = Object.entries(agentActivity)
    .map(([agent, count]) => `<tr><td>${agent}</td><td>${count}</td></tr>`)
    .join('\n');

  return `
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 640px; margin: 0 auto; padding: 20px; color: #e0e0e0; background: #1a1a2e;">
  <h1 style="color: #00d4aa; border-bottom: 2px solid #00d4aa; padding-bottom: 8px;">PatrickOS Daily Brief</h1>
  <p style="color: #aaa;">${date}</p>

  ${overdueCount > 0 ? `<div style="background: #3d1c1c; padding: 12px; border-radius: 6px; margin-bottom: 16px;">
    <strong style="color: #ff6b6b;">⚠️ ${overdueCount} overdue task${overdueCount > 1 ? 's' : ''}</strong>
  </div>` : ''}

  <h2 style="color: #ff6b6b;">🔴 Must-Do (P1)</h2>
  <ul>${tasksByPriority.P1.length ? renderTasks(tasksByPriority.P1) : '<li style="color:#666;">None</li>'}</ul>

  <h2 style="color: #ffa726;">🟡 Important (P2)</h2>
  <ul>${tasksByPriority.P2.length ? renderTasks(tasksByPriority.P2) : '<li style="color:#666;">None</li>'}</ul>

  <h2 style="color: #66bb6a;">🟢 Low Priority (P3)</h2>
  <ul>${tasksByPriority.P3.length ? renderTasks(tasksByPriority.P3) : '<li style="color:#666;">None</li>'}</ul>

  <h2 style="color: #42a5f5;">⚡ In Progress</h2>
  <ul>${[...tasksByPriority.P1, ...tasksByPriority.P2, ...tasksByPriority.P3, ...tasksByPriority.unset]
    .filter((t) => t.status === 'In Progress')
    .map((t) => `<li><strong>${t.task}</strong> · ${t.agentId || 'unassigned'}</li>`)
    .join('\n') || '<li style="color:#666;">None</li>'}</ul>

  <h2 style="color: #ab47bc;">🤖 Agent Activity</h2>
  <table style="border-collapse: collapse; width: 100%;">
    <tr><th style="text-align:left; padding:4px 8px; border-bottom:1px solid #333;">Agent</th><th style="text-align:left; padding:4px 8px; border-bottom:1px solid #333;">Active Tasks</th></tr>
    ${agentRows || '<tr><td colspan="2" style="color:#666;">No agent activity</td></tr>'}
  </table>

  <hr style="border-color: #333; margin-top: 24px;" />
  <p style="color: #666; font-size: 12px;">Generated by PatrickOS Accountability Engine</p>
</body>
</html>`;
}

export async function run() {
  console.log('[dailyDigest] Running...');

  const res = await fetch(`${API_BASE}/digest/daily`, {
    headers: { Authorization: `Bearer ${API_KEY}` },
  });

  if (!res.ok) {
    console.error('[dailyDigest] API call failed:', res.status, await res.text());
    return;
  }

  const digest = await res.json();
  const subject = `PatrickOS Daily Brief — ${formatDate()}`;

  await transporter.sendMail({
    from: `PatrickOS <${process.env.SMTP_USER}>`,
    to: process.env.DIGEST_EMAIL,
    subject,
    html: buildHtml(digest),
  });

  console.log(`[dailyDigest] Email sent to ${process.env.DIGEST_EMAIL}`);
}
