import nodemailer from 'nodemailer';
import { Client } from '@notionhq/client';

const API_BASE = `http://localhost:${process.env.PORT || 3200}/api/v1`;
const API_KEY = process.env.AGENT_API_KEY;
const WEEKLY_LOG_DB = '2da0e68b-cb87-8071-a160-000b62073621';

const notion = new Client({ auth: process.env.NOTION_TOKEN });

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT),
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

function weekOfDate() {
  const now = new Date();
  // Get Monday of the current week
  const day = now.getDay();
  const diff = now.getDate() - day + (day === 0 ? -6 : 1);
  const monday = new Date(now.setDate(diff));
  return monday.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
}

function buildHtml(digest) {
  const { weekOf, completed, dropped, deferred, agentStats, vaultCandidates } = digest;

  const taskList = (tasks) =>
    tasks.length
      ? tasks.map((t) => `<li><strong>${t.task}</strong> · ${t.domain || '—'} · ${t.agentId || 'unassigned'}</li>`).join('\n')
      : '<li style="color:#666;">None</li>';

  const agentRows = Object.entries(agentStats)
    .map(
      ([agent, s]) =>
        `<tr><td style="padding:4px 8px;">${agent}</td><td style="padding:4px 8px;">${s.completed}</td><td style="padding:4px 8px;">${s.total}</td></tr>`
    )
    .join('\n');

  return `
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 640px; margin: 0 auto; padding: 20px; color: #e0e0e0; background: #1a1a2e;">
  <h1 style="color: #00d4aa; border-bottom: 2px solid #00d4aa; padding-bottom: 8px;">PatrickOS Weekly Review</h1>
  <p style="color: #aaa;">Week of ${weekOf}</p>

  <h2 style="color: #66bb6a;">✅ Completed (${completed.length})</h2>
  <ul>${taskList(completed)}</ul>

  <h2 style="color: #ef5350;">❌ Dropped (${dropped.length})</h2>
  <ul>${taskList(dropped)}</ul>

  <h2 style="color: #ffa726;">⏳ Deferred / Waiting (${deferred.length})</h2>
  <ul>${taskList(deferred)}</ul>

  <h2 style="color: #ab47bc;">🤖 Agent Performance</h2>
  <table style="border-collapse: collapse; width: 100%;">
    <tr>
      <th style="text-align:left; padding:4px 8px; border-bottom:1px solid #333;">Agent</th>
      <th style="text-align:left; padding:4px 8px; border-bottom:1px solid #333;">Completed</th>
      <th style="text-align:left; padding:4px 8px; border-bottom:1px solid #333;">Total</th>
    </tr>
    ${agentRows || '<tr><td colspan="3" style="color:#666;">No agent stats</td></tr>'}
  </table>

  ${vaultCandidates.length ? `
  <h2 style="color: #42a5f5;">🔒 Vault Candidates</h2>
  <ul>${taskList(vaultCandidates)}</ul>` : ''}

  <hr style="border-color: #333; margin-top: 24px;" />
  <p style="color: #666; font-size: 12px;">Generated by PatrickOS Accountability Engine</p>
</body>
</html>`;
}

function buildNotionBlocks(digest) {
  const { completed, dropped, deferred, agentStats, vaultCandidates } = digest;

  const blocks = [];

  const addHeading = (text) =>
    blocks.push({ object: 'block', type: 'heading_2', heading_2: { rich_text: [{ text: { content: text } }] } });

  const addBullet = (text) =>
    blocks.push({ object: 'block', type: 'bulleted_list_item', bulleted_list_item: { rich_text: [{ text: { content: text } }] } });

  addHeading(`✅ Completed (${completed.length})`);
  if (completed.length) completed.forEach((t) => addBullet(`${t.task} · ${t.domain || '—'} · ${t.agentId || 'unassigned'}`));
  else addBullet('None');

  addHeading(`❌ Dropped (${dropped.length})`);
  if (dropped.length) dropped.forEach((t) => addBullet(`${t.task} · ${t.domain || '—'}`));
  else addBullet('None');

  addHeading(`⏳ Deferred (${deferred.length})`);
  if (deferred.length) deferred.forEach((t) => addBullet(`${t.task} · ${t.domain || '—'}`));
  else addBullet('None');

  addHeading('🤖 Agent Performance');
  for (const [agent, s] of Object.entries(agentStats)) {
    addBullet(`${agent}: ${s.completed} completed / ${s.total} total`);
  }

  if (vaultCandidates.length) {
    addHeading('🔒 Vault Candidates');
    vaultCandidates.forEach((t) => addBullet(t.task));
  }

  return blocks;
}

export async function run() {
  console.log('[weeklyReport] Running...');

  const res = await fetch(`${API_BASE}/digest/weekly`, {
    headers: { Authorization: `Bearer ${API_KEY}` },
  });

  if (!res.ok) {
    console.error('[weeklyReport] API call failed:', res.status, await res.text());
    return;
  }

  const digest = await res.json();
  const week = weekOfDate();
  const subject = `PatrickOS Weekly Review — Week of ${week}`;

  // Send email
  await transporter.sendMail({
    from: `PatrickOS <${process.env.SMTP_USER}>`,
    to: process.env.DIGEST_EMAIL,
    subject,
    html: buildHtml(digest),
  });
  console.log(`[weeklyReport] Email sent to ${process.env.DIGEST_EMAIL}`);

  // Create Notion page under Weekly OS Log DB
  const blocks = buildNotionBlocks(digest);
  await notion.pages.create({
    parent: { database_id: WEEKLY_LOG_DB },
    properties: {
      title: { title: [{ text: { content: `Weekly Review — Week of ${week}` } }] },
    },
    children: blocks,
  });
  console.log('[weeklyReport] Notion page created in Weekly OS Log');
}
